### ISSUE TITLE
Open Source License Missing.

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/PCSA-Android#451] opened 2017-04-02 11:30 UTC
It is said often that "Open source simply isn't open source without a proper license. Unless we have explicitly told others that they can modify and reuse our work, We've only showed others our code, We haven't shared it."

We can add GPL or AGPL license as it is most widely used across all open source projects.

Reference links:
[1] https://choosealicense.com/licenses/mit/
[2] https://github.com/blog/1964-open-source-license-usage-on-github-com

**Comment by sandarumk** [comment] 2017-04-03 03:55
duplicate of #180 . If you need any more discussion please continue on that thread. It would be great if you can add the links specified here in there.

**Closed as completed by sandarumk** 2017-04-03 03:55 UTC
Labels: duplicate
