### ISSUE TITLE
Message sending fails if an empty comrade is encountered.

### ISSUE THREAD

**Issue by yatna** [systers/PCSA-Android#39] opened 2016-02-11 17:37 UTC
If a comrade contact number is left empty, then message sending is failed for all comrades after that comrade. Example if comrade 1's contact number is left empty as shown:

![screenshot_2016-02-11-03-18-32](https://cloud.githubusercontent.com/assets/8321130/12984359/51bb813c-d113-11e5-8b6a-3c1e792c6b6e.png)

Then message is not send for comrades placed after comrade1 i.e 2,3,4,5,6 and failure message is dispalyed as shown.
![screenshot_2016-02-11-03-17-36](https://cloud.githubusercontent.com/assets/8321130/12984451/cddf8b46-d113-11e5-99ef-1ff5d8ddde57.png)

Similarly if comrade 3 is empty and rest are filled, then message is only sent to comrade 1,2 and fails for comrade 4,5,6. In this case also a failure message is displyed.

I would like to fix this issue .

**Comment by sandarumk** [comment] 2016-02-12 04:15
Can you do a Root Cause Analysis before fixing the issue. (RCA means you find the code segment and do an analysis on how the error occurs)

**Comment by yatna** [comment] 2016-02-14 14:55
In CircleOfTrustFragment.java , strings have been compared for nullity using != operator which is the incorrect way of comparing strings and hence gives incorrect result. != checks reference inequality and not content inequality. 


        try {
            sharedPreferences = this.getActivity().getSharedPreferences(Trustees.MyPREFERENCES, Context.MODE_PRIVATE);
            // The numbers variable holds the Comrades numbers
            String numbers[] = {sharedPreferences.getString(Trustees.comrade1, ""), sharedPreferences.getString(Trustees.comrade2, ""),
                    sharedPreferences.getString(Trustees.comrade3, ""), sharedPreferences.getString(Trustees.comrade4, ""),
                    sharedPreferences.getString(Trustees.comrade5, ""), sharedPreferences.getString(Trustees.comrade6, ""),};

            for(String number : numbers) {
                if(number != ""){
                    sms.sendTextMessage(number, null, message, null, null);
                }
            }
            AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
            builder.setTitle(R.string.msg_sent); // title bar string
            builder.setPositiveButton(R.string.ok, null);

            builder.setMessage(getString(R.string.confirmation_message));

            AlertDialog errorDialog = builder.create();
            errorDialog.show(); // display the Dialog

        }catch (Exception e)
        {
            Toast.makeText(getActivity(), R.string.message_failed, Toast.LENGTH_LONG).show();
        }
Here, the loop is entered even when  number is null . This raises an exception in sms.sendTextMessage(), as a result the loop is aborted and "message_failed" toast is displayed. Thus message is only sent until a null value is not encountered . 

When I compared strings for nullity using isEmpty(), the problem was solved and everything worked fine.

**Comment by sandarumk** [comment] 2016-02-15 03:47
Great!! You can go forward with this and submit a PR.

**Comment by yatna** [comment] 2016-02-22 11:22
PR submitted. #45

**Comment by sandarumk** [comment] 2016-02-22 15:56
merged.

**Closed by sandarumk** 2016-02-22 15:56 UTC
Labels: bug
