### ISSUE TITLE
ActionBar stretches onClicking the EditText in GlossaryFragment

### ISSUE THREAD

**Issue by pandilladivya** [systers/PCSA-Android#309] opened 2016-11-26 21:33 UTC
When a search is performed in **GlossaryFragment** ,the **ActionBar stretches** on activation of EditText.

![g1](https://cloud.githubusercontent.com/assets/16818129/20644041/2d54229e-b44e-11e6-84e3-7a30b417e4d1.PNG)

![g2](https://cloud.githubusercontent.com/assets/16818129/20643956/8fa88946-b44c-11e6-83fb-4502855b8969.PNG)

**Comment by pandilladivya** [comment] 2016-11-26 21:40
@sandarumk 

Kindly review the issue so that I can put a PR when done :)
Thanks!

**Comment by sandarumk** [comment] 2016-11-27 15:16
@pandilladivya I think this is some common issue with most of the screens. Can you find out what are the other screens which are having the same issue  and list them here. So it will be easy to fix the whole thing at once rather than reporting issue after issue and sending several PRs.

**Comment by rohands** [comment] 2016-11-27 15:35
@sandarumk @pandilladivya This issue was earlier pointed out by me and has been assigned to somebody else. Please cancel this issue @sandarumk

**Comment by rohands** [comment] 2016-11-27 15:37
To be more precise, #292 is the issue. @sandarumk Maybe you would want the person assigned with that issue to do all the necessary changes

**Comment by pandilladivya** [comment] 2016-11-27 15:45
@sandarumk @rohands 
Sorry!
My bad, I didn't notice..

**Comment by sandarumk** [comment] 2016-11-27 15:46
The reason I asked @pandilladivya to continue with finding all the other places where the issue exists is this.
1. She is active where the person whom the other issue is assigned is not active and haven't put a single reply for the issue in 21 days. So the probability of she turning up would be low.
2. The previous issue is in the preference activity and this issue is in another. That is why I wanted to check all the places. and if the person whom #292 is assigned showed up and wanted to do the change, she can do it where as all the other places can be fixed by @pandilladivya after she completed. 

@pandilladivya you can go ahead with finding all the places.

**Comment by codingblazer** [comment] 2016-11-27 15:55
@pandilladivya @sandarumk Just to save your time , I also figured this issue. The other places where issue exits are -
1. SignUp Activity (It doesn't appear first time.Just Press home button and return to app and you will find the problem)
2. Trustees Activity (Here keyboard covers the last comrade contact and thus edittext is not visible to user)
3. Glossary Activity (as pointed by you)
4. User Settings Activity

The problem seems related to keyboard as all these problems appear when keyboard opens up.

**Comment by pandilladivya** [comment] 2016-11-27 17:43
@codingblazer  You are right! The problem comes when the keyboard appears on the screen.
Currently, The problem exists when the user tries to input in the EditText.
Here are some screens where the issue comes into picture when the user tries to give some input.

![current](https://cloud.githubusercontent.com/assets/16818129/20649997/52b049a6-b4f2-11e6-9658-b4321adac798.PNG)

But,the problem doesn't end here.
For example: Check out this scenario

1. Open GlossaryFragment.

![8fa88946-b44c-11e6-83fb-4502855b8969](https://cloud.githubusercontent.com/assets/16818129/20650444/81876d8e-b4f4-11e6-98bb-d5781968c6c6.PNG)

2. Click on the SlidingMenu icon without closing the keyboard.

![menu](https://cloud.githubusercontent.com/assets/16818129/20650452/b5dfd580-b4f4-11e6-928a-f4924e186a72.PNG)

3. Choose any option.

Here are few Screenshots,

![more](https://cloud.githubusercontent.com/assets/16818129/20650460/ea4f0f3e-b4f4-11e6-87b2-628aa3a72a15.PNG)


Therefore,
This problem occurs in almost every screen in the application.

Kindly review 
@sandarumk @rohands 
Thank You

**Comment by sandarumk** [comment] 2016-11-27 17:48
Can you or @codingblazer please provide a Root Cause Analysis (what caused this) and a Description of the Fix (how to fix this) as well?

**Comment by pandilladivya** [comment] 2016-11-27 17:57
@sandarumk 
I have a fix for this.
We need to just add a property to the Layout.
Is it okay if I send a PR? 

Thank You :)

**Comment by pandilladivya** [comment] 2016-11-27 20:13
@rohands @sandarumk 
Here are few screenshots of the working application..

![new1](https://cloud.githubusercontent.com/assets/16818129/20651443/c2df2526-b50b-11e6-89ce-b7e56dd767ea.PNG)

![new2](https://cloud.githubusercontent.com/assets/16818129/20651442/c2debd02-b50b-11e6-85ed-9539976c5071.PNG)


Thanks :)

**Comment by sandarumk** [comment] 2016-11-28 16:20
Let's wait some time until  #292  is fixed and then you can continue on the rest. Remind me after about 10 days to come back to this issue if I already didn't put a reply.

**Comment by pandilladivya** [comment] 2016-11-28 16:33
@sandarumk 
Sure ma'm... Thank You :)

**Comment by sandarumk** [comment] 2016-12-20 15:08
#292 is fixed now. You can go ahead with this.

**Comment by sandarumk** [comment] 2017-01-17 16:42
Fixed via #358

**Closed as completed by sandarumk** 2017-01-17 16:42 UTC
Labels: Type: Bug
