### ISSUE TITLE
Role of Staff details very narrow

### ISSUE THREAD

**Issue by jacqueline8711** [systers/PCSA-Android#317] opened 2016-12-03 10:54 UTC
Support Services –> Confidentiality –> Role of Staff

The pop up with the details of Role of Staff is narrower than the other two which makes it more difficult to read:
![screenshot_20161203-114743](https://cloud.githubusercontent.com/assets/16260112/20858850/b2401f4e-b94e-11e6-9199-e1bed13595c3.png)
![screenshot_20161203-114748](https://cloud.githubusercontent.com/assets/16260112/20858849/b213315a-b94e-11e6-859d-1c160a0f9436.png)
Both should have the same width.

**Comment by sandarumk** [comment] 2016-12-03 17:59
What is the Android emulator/device you are using ?

**Comment by jacqueline8711** [comment] 2016-12-03 18:05
I was using my phone:
![screenshot_20161203-190121](https://cloud.githubusercontent.com/assets/16260112/20861246/56ed6c0e-b98b-11e6-9d68-e014e6e59068.png)
![screenshot_20161203-190125](https://cloud.githubusercontent.com/assets/16260112/20861247/571664f6-b98b-11e6-9b47-54a9752fb00a.png)

**Comment by rohands** [comment] 2016-12-03 18:07
@sandarumk Can I take over the issue?
@jacqueline8711 Could you please indicate how this view is different from the other two? And how you propose to solve the issue

**Comment by sandarumk** [comment] 2016-12-03 18:32
@rohands There is no such thing as taking over issues. This is an open community. You can contribute to any of the discussions and if you want to ask any questions, no one prevents you from asking them. And since @jacqueline8711 is a GCI student, at this stage we don't expect her to solve the issue or find the root cause.

**Comment by jacqueline8711** [comment] 2016-12-03 18:33
@rohands I don't know where the difference in the code is, the code of the "Role of Staff" section seems to be the same as the code of "Role of Volunteer Community" and "Role of Assaulted Volunteer".
@sandarumk I also tested it on an emulator (Nexus 5) and there it was narrower too, not as narrow but still there was a difference to the other two. So it's not just my phone

**Comment by rohands** [comment] 2016-12-03 18:35
@jacqueline8711 That's alright. I'll try to help you with this issue.
@sandarumk Oh okay, I wasn't aware of that. My apologies.

**Comment by rohands** [comment] 2016-12-03 18:36
@jacqueline8711 That is exactly why I asked you about that actually. Because the code is the same for all of them. But don't worry. We'll figure it out :)

**Comment by sandarumk** [comment] 2016-12-03 18:44
It happens because of this. https://github.com/systers/FirstAide-Android/pull/307/files. In here it changes text view to wrap content. When it changes to match parent, it works as expected. I should have forseen that before merging the PR. There can be several other places affected as well because of this.

**Comment by sandarumk** [comment] 2016-12-03 19:01
Changing back the text view properties did no harm to the issue at #294 as well even though it has been changed to fix that. The changes in the text view in the bystander fragment was enough to fix the issue. I am tagging this as GCI so any GCI student would come and claim and fix it to complete the task related to issue fixing.
@rohands Please confirm the fix and mention if you have any suggestions or improvements.

**Comment by sandarumk** [comment] 2017-01-17 16:28
Fixed via #361

**Closed as completed by sandarumk** 2017-01-17 16:28 UTC
Labels: Type: Bug
