### ISSUE TITLE
Confusing animations

### ISSUE THREAD

**Issue by jeffsieu** [systers/PCSA-Android#336] opened 2016-12-16 06:44 UTC
When going to another screen from pressing a button, the new screen animates in from the top. When pressing back to go to a previous screen, the current screen animates out to the left side. This may cause some confusion for app users.

**Steps to recreate**
1. From the main screen, press GET HELP NOW (The new screen animates in from the top)
2. From the GET HELP NOW screen, press back to return to the main screen. (The old, main screen animates in from the right)

**Comment by sandarumk** [comment] 2016-12-17 03:44
@XOptimistixX Can you claim this and submit it with the link to this issue?

**Comment by sandarumk** [comment] 2017-01-17 16:47
The expected fix would be removing the sliding down animations and go with more natural swiping right and left animation model.

**Comment by pandilladivya** [comment] 2017-01-17 17:15
@sandarumk 
Can I work on this Issue?

**Comment by sandarumk** [comment] 2017-01-17 17:18
I assigned you the issue which you were working on (The white screen one). You can claim this if this is not fixed after we come to a conclusion on what to be done there.

**Comment by madhavrathi** [comment] 2017-03-01 11:10
@sandarumk can i work on this ?

**Comment by sandarumk** [comment] 2017-03-01 15:18
@madhavrathi can you start with a beginner issue? Since @pandilladivya requested it first, let's give her a chance. 
@pandilladivya sorry for forgetting about this. Since we are at no end in the white screen issue, you can go forward with this?

**Comment by madhavrathi** [comment] 2017-03-01 15:22
@sandarumk  Cool !

**Comment by pandilladivya** [comment] 2017-03-01 17:15
@sandarumk Thank you ... will work on this :)

**Comment by sandarumk** [comment] 2017-03-04 18:09
@madhavrathi The issue is assigned to @pandilladivya and she is working on it.

**Comment by pandilladivya** [comment] 2017-03-05 11:31
@sandarumk Sorry for the delay.. 
I have raised a pull request. ( #404 )
Kindly Review
Thank you :)

**Closed as completed** 2017-03-12 11:05 UTC
Labels: enhancementType: Enhancement, Status: Available
