### ISSUE TITLE
check_duplicate_number function at Trustees.java has a bug

### ISSUE THREAD

**Issue by mari-linhares** [systers/PCSA-Android#166] opened 2016-03-19 17:17 UTC
If you fill the numbers as followed (just an example):
contact1 : 8644649
contact2 : 949464
contact3 : 111
contact4 : 111
There is no "duplicated number" message. But if you delete contact1 and contact2, then it works.

**Comment by AkankshaBodhankar** [comment] 2016-03-19 17:36
@mari-linhares I understood what the problem is. Thank you for reporting the bug.

**Comment by chamika** [comment] 2016-03-19 17:57
Let me explain the issues here

`check_duplicate_number() `
This is not the proper way of defining a Java method. It should be camelCase
Refer : [java code conventions](http://www.oracle.com/technetwork/java/codeconventions-135099.html)

Duplicate finding method
You do not need to check for each and every comparison between comrade numbers.
The CPU cost of `comrade1editText.getText().toString()` is higher here because of the multiple calls. Just use a `Set<String>` and check for contains when adding elements to it. It is the most efficient proved method of finding duplicates.
Refer : [Duplicate findings](http://stackoverflow.com/a/3951563)

`comrade1editText.getText().toString().equals("")`
Performance wise string equals has lower efficiency than retrieving length.
So better use `comrade1editText.getText().toString().length() == 0` for empty string check.

Remember to store in a string once you get toString() so that remove the unneccessary method calls
`String comrade1 = comrade1editText.getText().toString()`

**Comment by AkankshaBodhankar** [comment] 2016-03-19 18:03
@chamika That's great information. will work accordingly now on :-)

**Comment by mari-linhares** [comment] 2016-03-19 18:09
No problem @AkankshaBodhankar but do it like @chamika explained it. And if it is not a problem for you I think it would be a good idea to change the name of the function to something more descritive (it returns true if there isn't a duplicated number, so a name like "no_duplicate_number()" would be better for understanding it);

**Comment by AkankshaBodhankar** [comment] 2016-03-19 18:12
@mari-linhares Thank you. I'll change it accordingly :-) and the name too

**Comment by AkankshaBodhankar** [comment] 2016-03-19 18:59
@mari-linhares @chamika Thank you for such great feedback and information guys. Learned new things :-)

**Comment by AkankshaBodhankar** [comment] 2016-03-31 17:56
Fixed and merged I think this issue can be now closed @mari-linhares

**Comment by sandarumk** [comment] 2016-03-31 18:07
Merged.

**Closed by sandarumk** 2016-03-31 18:07 UTC
Labels: accepted, bug
