### ISSUE TITLE
Appropriate hint for edit text in My Trustees. 

### ISSUE THREAD

**Issue by ashu-dadhich** [systers/PCSA-Android#330] opened 2016-12-13 16:40 UTC
**Summary:**

Appropriate hint for edit text in My Trustees in **Circle of Trust**

**Steps to reproduce:**

Change it in strings.xml

**Expected behavior:**

Contact No * should be displayed as hint in edit text. 

**Observed behavior:**

instead of Name * as hint in edit text.

**Device and Android version:**

Era X1 (Android Marshmallow)

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/15179401/21149153/8d3597a8-c180-11e6-9cac-ccb09262e606.png)

**Comment by ashu-dadhich** [comment] 2016-12-13 16:43
**also when we try to enter number into Emergency Contact no 6 the soft keyboard hides it **

I want to correct it as well. 
Thank you

**Comment by sandarumk** [comment] 2016-12-13 16:58
This issue has been reported before and there has even been PRs to resolve. But this is what peacecorps wanted in their designs. (Refer the mockup). Regarding the second issue, please explain it bit further.
One more important thing is you have misunderstood the meaning of steps to reproduce. In steps to reproduce you have to give the step by step process you did to find the bug so that we can do the same and encounter the bug.

**Comment by ashu-dadhich** [comment] 2016-12-13 17:22
![image](https://cloud.githubusercontent.com/assets/15179401/21150926/bfb9083a-c186-11e6-85e6-1c94aa76f5c1.png)
Here when we are entering in name 6 it gets hidden by soft keyboard.

**Comment by codingblazer** [comment] 2016-12-13 17:25
@top-gun007 I reported this in #309 and it is being fixed by someone.

**Comment by ashu-dadhich** [comment] 2016-12-13 17:29
Oh I am sorry I had my exams going on recently so I didn't notice.
If its alright @sandarumk can I close it then.

**Comment by sandarumk** [comment] 2016-12-13 17:33
I will close it. When you are reporting the issues at least go through the current issue list in the repository to ensure that you are not duplicating anything.  It is preferred to go through the closed issues since they will give you a good idea on what kind of issues are accepted or what kind of issues are rejected.

**Closed as completed by sandarumk** 2016-12-13 17:33 UTC
Labels: duplicate

**Comment by ashu-dadhich** [comment] 2016-12-13 17:35
ok I will :+1:
