### ISSUE TITLE
If Permission Denied for SMS

### ISSUE THREAD

**Issue by scopeInfinity** [systers/PCSA-Android#58] opened 2016-02-22 17:49 UTC
When Application is asking for permission, if we denied it now or maybe set to 'Always Deny' earlier. Then it didn't perform any check and simply show "Message Sent" without awareness of user.

**Comment by scopeInfinity** [comment] 2016-02-22 17:51
![12755186_953685814668365_1844494078_o](https://cloud.githubusercontent.com/assets/9819066/13227090/db201b2c-d9ba-11e5-8ab3-ef64fcb4cfc1.jpg)

![12751938_953685411335072_431895695_o](https://cloud.githubusercontent.com/assets/9819066/13227091/e17b6c60-d9ba-11e5-81c0-a9cb8e0fb945.jpg)

**Comment by sandarumk** [comment] 2016-02-26 16:31
Thank you for reporting. Do you like to fix this issue?

**Comment by scopeInfinity** [comment] 2016-02-27 15:09
Yes, I would like to fix the issue.
Should I check permission for Phone call also?

**Comment by sandarumk** [comment] 2016-02-27 15:16
Great! First can you give an analysis on why this is happening? There is current development going on in the same activity. You can start this as soon as that PR is merged to the system. But first do the root cause analysis.  Why do you need to check for the phone call here?

**Comment by scopeInfinity** [comment] 2016-02-28 20:25
@sandarumk 
Initially I though its just Android permission but I guess it's not.

First normal Permission prompt
![aqua_power_hd_2016-02-29-01-51-26](https://cloud.githubusercontent.com/assets/9819066/13381645/0c2d37ba-de87-11e5-93a1-a8d63ac31379.png)

Then second prompt is kind of secondary level permission : Shown in First comment
![permission_prompt](https://cloud.githubusercontent.com/assets/9819066/13227090/db201b2c-d9ba-11e5-8ab3-ef64fcb4cfc1.jpg)

I tried to find the root cause for the shown message but I got no success. This is problem I am facing in my phone not in the emulator.
Any guide for this root analysis.

**Comment by scopeInfinity** [comment] 2016-02-28 20:28
What about instead of just flashing `Message Send`, we can show `Trying to send Message` then after certain time period checking depending upon message is actually send or not showing suitable Dialogue Message.

**Comment by chamika** [comment] 2016-02-29 17:50
This is a feature inherited from Android OS. This dialog popups when an application tries to send a message to a Premium number (Ex: 1234, 1111). Premium numbers are short numbers which are allocated to network providers.

If you implement `ArrayList<PendingIntent> sentIntents` in method call ` sms.sendMultipartTextMessage(number, null, parts, null, null);` 
you can capture whether the SMS sending allowed or blocked by the user.

Please refer this [answer](http://stackoverflow.com/a/8579311/872165) for implementation.

**Comment by sandarumk** [comment] 2016-02-29 17:58
Thank you Chamika for the explanation. @scopeInfinity there is no need of two messages trying to send and sent.

**Comment by scopeInfinity** [comment] 2016-02-29 18:27
Thanks @chamika !
@sandarumk It means there is nothing in this Issue that needed to be solved, Right?

**Comment by sandarumk** [comment] 2016-02-29 18:32
If you want you can solve this issue following @chamika 's comments. But since there is a very low probability of adding a premium number as a comrade, there is no need of solving the issue. Hence, closing the issue.

**Comment by scopeInfinity** [comment] 2016-02-29 18:33
OK

**Closed by sandarumk** 2016-02-29 18:32 UTC
